# 1 Pod:  This is a layer of abstraction on top of a container. 
# This is the smallest object that kubernetes can work on. 
# In the pod, we have the container. 
# kubectl commands will work on the pod and pod communicates there instructions to the container.
# kubectl run --image tomcat   webserver
# ( Webserver is pod name )
# To see list of pods
# ------------------------
# kubectl get pods
# If we do not specify replicas, it creates only one replica.
# To delete the pod
# --------------------
# kubectl delete pods webserver
# Lets create pod again
# -----------------------
# kubectl run --image tomcat webserver
# To know on which node, this pod is running
# kubectl get pods -o wide
# ( o - stands for output )

#  to create a pod using kubernetes manifest

apiVersion: v1
kind: Pod
metadata:
 name: webserver
 labels:
  app: api
spec:
 containers: 
  - name: nginx
    image: nginx

