apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_PASSWORD: demo_password
  POSTGRES_USER: demo_user
  POSTGRES_DB: demodb
  API_KEY: alskdlaskdlaksnlaksnde823948rnwelkdflaskflaskdj
# ---
# # using envfrom
# apiVersion: v1
# kind: Pod
# metadata:
#  name: postgres-pod
#  labels:
#   author: aziz
#   type: database
# spec:
#  containers:
#   - name: mypostgres
#     image: postgres
#     envFrom:
#       - configMapRef:
#           name: postgres-config
---
# using valuefrom
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  author: aziz
  type: database
spec:
 containers:
  - name: mypostgres
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: POSTGRES_PASSWORD
     - name: POSTGRES_USER
       valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: POSTGRES_USER
     - name: POSTGRES_DB
       valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: POSTGRES_DB