apiVersion: v1
kind: Pod
metadata:
 name: webserver
 labels:
  app: api
spec:
 containers: 
  - name: nginx
    image: nginx
---

apiVersion: v1
kind: Service
metadata:
  name: console-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007