# Deployment Object
# -------------------------
# This is also an high level object which can be used for scalling, load balancing and perform rolling updates.

# Create a deployment file to run nginx 1.7.9 with 3 replicas. 
# Later perform a rolling update to nginx 1.9.1 
# vim deployment.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  author: aziz
  type: proxyserver
spec:
 replicas: 3
 selector:
  matchLabels:
   type: proxyserver
 template:
  metadata:
   name: nginx-pod
   labels:
    type: proxyserver
  spec:
   containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
       - containerPort: 80
         hostPort: 8888
