# ReplicationController:
# This is an high level object used for handling multiple replicas of a specific pod. Here we can perform load balancing and scalling.
# ReplicationController uses keys like replicas, template" etc in the "spec" section.
# In template section we can give metadata related to the pod and also use another spec section where we can give containers information.
# Ex: Create  a replication controller for creating 3 replicas of httpd
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx-app
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

        