--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pl-test
  region: eu-north-1

vpc:
  cidr: "192.168.0.0/16"  
  subnets:
    public:
      private-one:
        cidr: "192.168.128.0/19" 
      private-two:
        cidr: "192.168.64.0/19"  
  clusterEndpoints:
    publicAccess: true
    privateAccess: true 

nodeGroups:
  - name: pl-node-gp
    instanceType: t2.medium
    desiredCapacity: 2
