apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-west-1
  # version: "1.25"

# vpc:
#   cidr: 10.10.0.0/16
#   autoAllocateIPv6: true
#   hostnameType: resource-name
#   # disable public access to endpoint and only allow private access
#   clusterEndpoints:
#     publicAccess: false
#     privateAccess: true

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
